export const cardConstants = {
  ADD_NEW_TASK: "ADD_NEW_TASK",
  DELETE_TASK: "DELETE_TASK",
  MARK_COMPLETE: "MARK_COMPLETE",
  SHOW_ALL_TASKS: "SHOW_ALL_TASKS",
  SHOW_ACTIVE_TASKS: "SHOW_ACTIVE_TASKS",
  SHOW_COMPLETE_TASKS: "SHOW_COMPLETE_TASKS",
  CLEAR_COMPLETED_TASKS: "CLEAR_COMPLETED_TASKS"
}